---
name: noip-renewer-base
version: 2026.06.2
slug: noip-renewer-base
description: "simao-silva/noip-renewer for homeassistant addon"
url: "https://github.com/habuild/noip-renewer/tree/main/noip-renewer"
image: "ghcr.io/habuild/noip-renewer-base"
arch:
  - aarch64
  - amd64
