FROM python:3.10.7-slim-bullseye@sha256:04a4e3f8fae018a92e082d7f18285d2e5058cee77a7fa5374c832f328a1b5c20

ARG PIP_VERSION
ARG SELENIUM_VERSION
ARG GOOGLETRANS_VERSION
ARG REQUESTS_VERSION

ENV DEBIAN_FRONTEND=noninteractive

ARG ARMV7_DEPS="gcc libc6-dev libffi-dev rustc cargo libssl-dev"

RUN apt-get update && \
    if [ $(getconf LONG_BIT) -eq 32 ]; then apt-get install -y --no-install-recommends ${ARMV7_DEPS}; fi

RUN pip install --no-cache-dir pip=="${PIP_VERSION}" && \
    pip install --no-cache-dir --user selenium=="${SELENIUM_VERSION}" googletrans=="$GOOGLETRANS_VERSION" requests=="$REQUESTS_VERSION"



FROM python:3.10.7-slim-bullseye@sha256:04a4e3f8fae018a92e082d7f18285d2e5058cee77a7fa5374c832f328a1b5c20

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends chromium chromium-driver && \
    apt-get clean && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* /usr/share/doc /usr/share/man

COPY --from=0 /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

COPY renew.py renew.py

ENTRYPOINT ["python3", "renew.py"]
