FROM python:3.10.3-slim-bullseye@sha256:b5facd050e0ad2c9b613b1735c52d55e09bb40e95fc36281ff3597a4cdea3687

ARG PIP_VERSION
ARG SELENIUM_VERSION="3.141.0"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    pip install --no-cache-dir pip=="$PIP_VERSION" && \
    pip install --no-cache-dir --user selenium=="$SELENIUM_VERSION"



FROM python:3.10.3-slim-bullseye@sha256:b5facd050e0ad2c9b613b1735c52d55e09bb40e95fc36281ff3597a4cdea3687

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends chromium chromium-driver && \
    apt-get clean && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* /usr/share/doc /usr/share/man

COPY --from=0 /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

COPY renew-legacy.py renew.py

ENTRYPOINT ["python3", "renew.py"]