FROM python:3.12.0-slim-bullseye@sha256:c740b8691a28975380a1b8f01a75bb12213a9294f2f2cf7d83b2c160c647817f

SHELL ["/bin/bash", "-c"]

ARG PIP_VERSION
ENV DEBIAN_FRONTEND=noninteractive
ARG ARMV7_DEPS="gcc libc6-dev libffi-dev rustc cargo libssl-dev"

RUN apt-get update && \
    if [ $(getconf LONG_BIT) -eq 32 ]; then apt-get install -y --no-install-recommends ${ARMV7_DEPS}; fi

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir pip=="${PIP_VERSION}" && \
    pip install --no-cache-dir --user -r /requirements.txt



FROM python:3.12.0-slim-bullseye@sha256:c740b8691a28975380a1b8f01a75bb12213a9294f2f2cf7d83b2c160c647817f

SHELL ["/bin/bash", "-c"]

ARG GECKO_DRIVER_VERSION
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl

RUN set -x && \
    if [ "$(uname --m)" == "x86_64" ]; then ARCH="linux64"; elif [ "$(uname --m)" == "aarch64" ]; then ARCH="linux-aarch64"; else ARCH="linux32"; fi && \
    curl -sSL -O https://github.com/mozilla/geckodriver/releases/download/v${GECKO_DRIVER_VERSION}/geckodriver-v${GECKO_DRIVER_VERSION}-${ARCH}.tar.gz && \
    tar zxf geckodriver-v${GECKO_DRIVER_VERSION}-${ARCH}.tar.gz



FROM python:3.12.0-slim-bullseye@sha256:c740b8691a28975380a1b8f01a75bb12213a9294f2f2cf7d83b2c160c647817f

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends firefox-esr && \
    apt-get clean && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* /usr/share/doc /usr/share/man

COPY --from=0 /root/.local /root/.local
COPY --from=1 /geckodriver /usr/local/bin/geckodriver

ENV PATH=/root/.local/bin:$PATH

COPY renew.py renew.py

ENTRYPOINT ["python3", "renew.py"]
