FROM python:3.12.0-alpine@sha256:4fb2cdab707593459d021cbc776add5fe4642708ae1f0831a1df358fa637fc4c

RUN apk add --no-cache gcc libc-dev libffi-dev && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --user selenium googletrans=="3.1.0a0" requests


FROM python:3.12.0-alpine@sha256:4fb2cdab707593459d021cbc776add5fe4642708ae1f0831a1df358fa637fc4c

RUN apk add --no-cache chromium chromium-chromedriver && \
    rm -rf /var/cache/apk/* /tmp/* /usr/share/doc

COPY --from=0 /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

ADD renew.py .

ENTRYPOINT ["python3", "renew.py"]
